### ISSUE TITLE
Compile for Patmos

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos-llvm-project#3]
The compiler in the current version does not compile the C code in the Patmos hardware. Example issues:

```error: unknown argument: ‘-mpatmos-disable-vliw’```

```expanded from macro ‘exc_prologue’
        : “$r1”, “$r2", “$r3”,          \
         ^
ethlib/tte.c:484:3: error: unknown register name ‘$r1’ in asm
```

**Comment by schoeberl** [comment]
If possible for the transition phase it would be good to use the C preprocessor to select between old and new syntax.

It is not so important in which repo this issue is, but for me it looks like a change in the compiler ;)

**Comment by Emoun** [comment]
I'm closing this issue because it does not require any action on its own.
